language: php
sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update
  - cp config/config.secret.php{.placeholder,}

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
